package com.alibou.security.company;

public enum Category {
    FRESH_PRODUCE,
    MEAT_AND_POULTRY,
    SEAFOOD,
    DAIRY_AND_EGGS,
    GRAINS_AND_BAKERY,
    CANNED_AND_PACKAGED_GOODS,
    BEVERAGES,
    FROZEN_FOODS,
    SNACKS_AND_CONFECTIONERY,
    ORGANIC_AND_SPECIALTY_FOODS,
    ETHNIC_FOODS,
    HEALTH_AND_WELLNESS,
    BULK_AND_WHOLESALE,
    GOURMET_AND_SPECIALTY,
    FOOD_SERVICE_EQUIPMENT_AND_SUPPLIES
}